services:
  controller.StatusGet:
    class: ../../../Api/controllers/status/CheckStatusController
    arguments: []

  controller.BorrowerPost:
    class: ../../../Api/controllers/borrower/CreateBorrowerController
    arguments: ["CreateBorrower"]

  CreateBorrower:
    class: ../../../Application/features/borrowers/CreateBorrower/CreateBorrower
    arguments: ["BorrowerRepository"]

    BorrowerRepository:
    class: ../../../Persistence/repositories/FileBorrowerRepository
    argument: []