services:
  controller.StatusGet:
    class: ../../controllers/status/CheckStatusController
    arguments: []

  controller.BorrowerPost:
    class: ../../controllers/borrower/CreateBorrowerController
    arguments: [""]
